In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
reg = linear_model.LinearRegression()


In [13]:
df=pd.read_csv('Add_sales_data_2018.csv')
df
df=df.drop(['Date'], axis=1)
df

Add1(in Thousands)  Add2(in Thousands)  Add3(in Thousands)  \
0                208.00              222.25              206.85   
1                217.00              218.60              205.90   
2                223.50              227.80              216.15   
3                230.00              237.50              225.75   
4                234.55              234.60              221.05   
..                  ...                 ...                 ...   
200              288.00              288.25              279.20   
201              290.00              292.50              282.20   
202              298.60              298.60              286.65   
203              290.00              299.55              285.90   
204              287.55              289.90              285.05   

     Add4(in Thousands)  Add5(in Thousands)  Profit(in Thousands)  
0                216.00              215.15              4093.065  
1                210.25              209.20              4042.448  
2                217.25              218.20              4213.819  
3                226.45              227.60              4391.665  
4                230.30              230.90              4350.683  
..                  ...                 ...                   ...  
200              284.50              284.30              5374.105  
201              284.80              284.45              5439.655  
202              287.45              287.80              5545.013  
203              297.85              298.35              5565.444  
204              288.05              288.45              5421.842  

[205 rows x 6 columns]

In [12]:
arr = df.to_numpy()
arr

array([[ 208.   ,  222.25 ,  206.85 ,  216.   ,  215.15 , 4093.065],
       [ 217.   ,  218.6  ,  205.9  ,  210.25 ,  209.2  , 4042.448],
       [ 223.5  ,  227.8  ,  216.15 ,  217.25 ,  218.2  , 4213.819],
       ...,
       [ 298.6  ,  298.6  ,  286.65 ,  287.45 ,  287.8  , 5545.013],
       [ 290.   ,  299.55 ,  285.9  ,  297.85 ,  298.35 , 5565.444],
       [ 287.55 ,  289.9  ,  285.05 ,  288.05 ,  288.45 , 5421.842]])

In [5]:
from sklearn.model_selection import train_test_split


In [33]:
X=arr[:,0:5]
X
Y=arr[:,5]
X

array([[208.  , 222.25, 206.85, 216.  , 215.15],
       [217.  , 218.6 , 205.9 , 210.25, 209.2 ],
       [223.5 , 227.8 , 216.15, 217.25, 218.2 ],
       ...,
       [298.6 , 298.6 , 286.65, 287.45, 287.8 ],
       [290.  , 299.55, 285.9 , 297.85, 298.35],
       [287.55, 289.9 , 285.05, 288.05, 288.45]])

In [34]:
df.corr()

Add1(in Thousands)  Add2(in Thousands)  \
Add1(in Thousands)              1.000000            0.990976   
Add2(in Thousands)              0.990976            1.000000   
Add3(in Thousands)              0.986274            0.987990   
Add4(in Thousands)              0.976365            0.989921   
Add5(in Thousands)              0.976716            0.990285   
Profit(in Thousands)            0.991975            0.999145   

                      Add3(in Thousands)  Add4(in Thousands)  \
Add1(in Thousands)              0.986274            0.976365   
Add2(in Thousands)              0.987990            0.989921   
Add3(in Thousands)              1.000000            0.991343   
Add4(in Thousands)              0.991343            1.000000   
Add5(in Thousands)              0.991908            0.999699   
Profit(in Thousands)            0.993389            0.993346   

                      Add5(in Thousands)  Profit(in Thousands)  
Add1(in Thousands)              0.976716              0.991975  
Add2(in Thousands)              0.990285              0.999145  
Add3(in Thousands)              0.991908              0.993389  
Add4(in Thousands)              0.999699              0.993346  
Add5(in Thousands)              1.000000              0.993710  
Profit(in Thousands)            0.993710              1.000000

In [35]:
x_train, x_test, y_train, y_test = train_test_split(X,Y)

In [36]:
x_train

array([[265.95, 269.9 , 261.1 , 262.9 , 262.15],
       [302.9 , 303.7 , 286.1 , 291.15, 290.65],
       [246.5 , 252.35, 245.55, 250.  , 250.2 ],
       [274.65, 274.65, 266.05, 267.  , 267.05],
       [265.  , 268.85, 262.2 , 266.5 , 266.6 ],
       [235.  , 238.5 , 235.  , 237.4 , 237.55],
       [252.2 , 259.4 , 252.2 , 258.5 , 257.85],
       [271.55, 276.85, 269.15, 274.9 , 275.35],
       [223.45, 236.7 , 223.3 , 234.  , 233.95],
       [240.  , 240.  , 232.5 , 235.  , 234.25],
       [271.  , 273.1 , 263.25, 264.5 , 264.45],
       [263.  , 268.25, 261.45, 265.05, 263.95],
       [251.05, 258.9 , 250.  , 258.2 , 257.9 ],
       [301.  , 306.35, 299.7 , 302.8 , 302.75],
       [268.7 , 274.2 , 261.65, 263.  , 262.85],
       [262.75, 266.7 , 260.35, 265.55, 265.75],
       [275.  , 281.65, 273.  , 276.75, 277.8 ],
       [248.4 , 249.6 , 232.7 , 238.1 , 238.65],
       [236.05, 242.  , 235.95, 240.35, 239.35],
       [273.9 , 277.8 , 271.65, 273.9 , 273.85],
       [237.9 , 239.

In [37]:
reg.fit(x_train,y_train)

LinearRegression()

In [38]:
reg.coef_

array([ 1.  , 12.38,  3.5 ,  1.  ,  0.9 ])

In [39]:
reg.predict([[290,321,309,298,320]])

array([5931.48])